openapi: 3.0.3

info:
  title: IMB Products Management API
  description: IMB Products Management API allows you to remotely manage IMB Products.
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: health
    description: Health check

  - name: product
    description: Products management

paths:
  /api/health:
    get:
      summary: Check API health
      tags: [health]
      deprecated: false
      responses:
        200:
          description: OK

  /api/products:
    get:
      summary: Find all the products
      tags: [product]
      deprecated: false
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        400:
          description: Failed reading the products

  /api/product:
    post:
      summary: Add a new product
      tags: [product]
      deprecated: false
      requestBody:
        description: Create a new product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Failed creating a new product

  /api/product/{id}:
    put:
      tags:
        - product
      summary: Update an existing product
      description: Update an existing product by Id
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: ID of product to update
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        description: Update an existent product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatedProduct'
        required: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Failed updating an existing product
        404:
          description: Invalid ID provided

components:
  schemas:
    Product:
      allOf:
        - type: object
          properties:
            productId:
              $ref: '#/components/schemas/ID'
          required:
            - productId
        - $ref: '#/components/schemas/NewProduct'

    NewProduct:
      type: object
      properties:
        productName:
          type: string
        productOwnerName:
          type: string
        developers:
          type: array
          items:
            type: string
          minItems: 1
          maxItems: 5
        scrumMasterName:
          type: string
        startDate:
          type: string
          format: date-time
        methodology:
          type: string
          enum: [Agile, Waterfall]
      required:
        - productName
        - productOwnerName
        - developers
        - scrumMasterName
        - startDate
        - methodology

    UpdatedProduct:
      type: object
      properties:
        productName:
          type: string
        productOwnerName:
          type: string
        developers:
          type: array
          items:
            type: string
          minItems: 1
          maxItems: 5
        scrumMasterName:
          type: string
        methodology:
          type: string
          enum: [Agile, Waterfall]

    ID:
      type: string
      format: uuid
